ESTADOS_BRASILEIROS = [
    "ACRE",
    "ALAGOAS",
    "AMAPÁ",
    "AMAZONAS",
    "BAHIA",
    "CEARÁ",
    "DISTRITO FEDERAL",
    "ESPÍRITO SANTO",
    "GOIÁS",
    "MARANHÃO",
    "MATO GROSSO",
    "MATO GROSSO DO SUL",
    "MINAS GERAIS",
    "PARÁ",
    "PARAÍBA",
    "PARANÁ",
    "PERNAMBUCO",
    "PIAUÍ",
    "RIO DE JANEIRO",
    "RIO GRANDE DO NORTE",
    "RIO GRANDE DO SUL",
    "RONDÔNIA",
    "RORAIMA",
    "SANTA CATARINA",
    "SÃO PAULO",
    "SERGIPE",
    "TOCANTINS",
]

COLUMNS = [
    "NM_BENEFICIARIO",
    "NM_NIVEL",
    "AN_INICIO",
    "AN_FIM",
    "NM_IES_ORIGEM_PRINCIPAL_DA",
    "NM_IES_ESTUDO_PRINCIPAL_DA",
    "NM_AREA_AVALIACAO",
    "NM_UF_IES_ORIGEM",
    "NM_PAIS_IES_ESTUDO",
]

COLUMN_RENAME = [
    "nome_beneficiario",
    "nivel_bolsa",
    "ano_inicio_bolsa",
    "ano_fim_bolsa",
    "nome_ies_origem",
    "nome_ies_destino",
    "area_avaliacao",
    "uf_ies_origem",
    "pais_ies_destino",
]

DOUTOR_TERMS = [
    "DOUTORADO PLENO",
    "DOUTORADO SANDUÍCHE",
    "DOUTOR PLENO",
    "DOUTOR SÊNIOR",
    "DOUTOR JÚNIOR",
    "JOVEM DOUTOR",
    "ESTÁGIO PÓS-DOUTORAL",
    "PÓS-DOUTORADO",
    "ESTÁGIO SÊNIOR",
    "PESQUISADOR VISITANTE ESPECIAL",
    "PROFESSOR VISITANTE",
    "PROFESSOR VISITANTE SÊNIOR",
    "PROFESSOR VISITANTE JÚNIOR",
    "PROFESSOR VISITANTE DO EXTERIOR SÊNIOR",
    "PROFESSOR VISITANTE DO EXTERIOR PLENO",
    "PROFESSOR/PESQUISADOR VISITANTE NO EXTERIOR",
    "PROFESSOR CONVIDADO",
]

LINGUA_UNIVERSIDADES = {
    "ex_1": "Português",
    "ex_2": "Português",
    "ex_3": "Inglês",
    "ex_4": "Português",
    "ex_5": "Português",
    "ex_6": "Espanhol",
    "ex_7": "Português",
    "ex_8": "Inglês",
    "ex_9": "Francês",
    "ex_10": "Português",
    "ex_11": "Francês",
    "ex_12": "Espanhol",
    "ex_13": "Espanhol",
    "ex_14": "Francês",
    "ex_15": "Espanhol",
    "ex_16": "Inglês",
    "ex_17": "Espanhol",
    "ex_18": "Francês",
    "ex_19": "Espanhol",
    "ex_20": "Francês",
    "ex_21": "Inglês",
    "ex_22": "Inglês",
    "ex_23": "Inglês",
    "ex_24": "Espanhol",
    "ex_25": "Espanhol",
    "ex_26": "Italiano",
    "ex_27": "Francês",
    "ex_28": "Inglês",
    "ex_29": "Espanhol",
    "ex_30": "Espanhol",
    "ex_31": "Inglês",
    "ex_32": "Francês",
    "ex_33": "Espanhol",
    "ex_34": "Alemão",
    "ex_35": "Espanhol",
    "ex_36": "Italiano",
    "ex_37": "Inglês",
    "ex_38": "Inglês",
    "ex_39": "Inglês",
    "ex_40": "Francês",
    "ex_41": "Espanhol",
    "ex_42": "Inglês",
    "ex_43": "Dinamarquês",
    "ex_44": "Espanhol",
    "ex_45": "Alemão",
    "ex_46": "Inglês",
    "ex_47": "Francês",
    "ex_48": "Espanhol",
    "ex_49": "Holandês",
    "ex_50": "Inglês",
    "ex_51": "Espanhol",
    "ex_52": "Inglês",
    "ex_53": "Italiano",
    "ex_54": "Alemão",
    "ex_55": "Inglês",
    "ex_56": "Inglês",
    "ex_57": "Francês",
    "ex_58": "Francês",
    "ex_59": "Francês",
    "ex_60": "Inglês",
    "ex_61": "Alemão",
    "ex_62": "Inglês",
    "ex_63": "Inglês",
    "ex_64": "Espanhol",
    "ex_65": "Inglês",
    "ex_66": "Inglês",
    "ex_67": "Inglês",
    "ex_68": "Francês",
    "ex_69": "Holandês",
    "ex_70": "Inglês",
    "ex_71": "Inglês",
    "ex_72": "Inglês",
    "ex_73": "Inglês",
    "ex_74": "Francês",
    "ex_75": "Alemão",
    "ex_76": "Inglês",
    "ex_77": "Português",
    "ex_78": "Italiano",
    "ex_79": "Italiano",
    "ex_80": "Francês",
    "ex_81": "Francês",
    "ex_82": "Português",
    "ex_83": "Português",
    "ex_84": "Espanhol",
    "ex_85": "Inglês",
    "ex_86": "Espanhol",
    "ex_87": "Português",
    "ex_88": "Francês",
    "ex_89": "Espanhol",
    "ex_90": "Alemão",
    "ex_91": "Inglês",
    "ex_92": "Inglês",
    "ex_93": "Espanhol",
    "ex_94": "Inglês",
    "ex_95": "Espanhol",
    "ex_96": "Inglês",
    "ex_97": "Inglês",
    "ex_98": "Inglês",
    "ex_99": "Francês",
}
